// Generated by CoffeeScript 1.4.0
(function() {
  var init;

  Backbone.sync = Nimbus.backbone_sync;

  Nimbus.Auth.authorized_callback = function() {
    return init();
  };

  init = function() {
    if (Nimbus.Auth.authorized()) {
      $("#loading").fadeOut();
      $("#todoapp").trigger('auth_event');
      return console.log('authorized_callback');
    }
  };

}).call(this);
